server:
  port: 8989

spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://127.0.0.1:3306/bsx_blog?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-circular-references: true
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#    default-property-inclusion: non_null
  redis:
    database: 0
    host: 192.168.244.138
    port: 6379
    password: 21
    connect-timeout: 60s
    timeout: 120s
    lettuce:
      pool:
        max-wait: 60s # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-active: 20 #连接池最大连接数（使用负值表示没有限制） 默认 8
        max-idle: 10 # 连接池中的最大空闲连接 默认 8
        min-idle: 5 # 连接池中的最小空闲连接 默认 0
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

mybatis-plus:
  type-aliases-package: com.bsxjzb.domain.po
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
  mapper-locations: classpath:/mapper/**/*.xml

log:
  level: info
  path: ./logs

springfox:
  documentation:
    enabled: true

oss:
  accessKey: 1J6jMvHuAB-dVzyFgavUBbEpbS4dIQzy7qKSCC1y
  secretKey: Tu43QglpIBg4-lGBhA9UlXxJ_iScB2CblHR-uC-n
  bucket: bsx-jzb-blog01
  outLink: http://rsqxyotjk.bkt.clouddn.com/